### ISSUE TITLE
pytorch example is not working

### ISSUE THREAD

**Issue by devxoxo** [kubeflow/katib#1112]
/kind bug

**What steps did you take and what happened:**
I am trying to run [a pytorch example](https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/pytorchjob-example.yaml)
But it is not working as follows.
Master pods keep crashing with "CrashLoopBackOff"
```
vagrant@minikf:~$ kubectl get pods -n kubeflow-user
NAME                                         READY   STATUS             RESTARTS   AGE
pytorchjob-example-82cjcqdz-master-0         0/2     CrashLoopBackOff   8          2m32s
pytorchjob-example-82cjcqdz-worker-0         0/1     Init:1/2           0          2m31s
pytorchjob-example-82cjcqdz-worker-1         0/1     Init:1/2           0          2m30s
pytorchjob-example-bq7fbhnb-master-0         0/2     CrashLoopBackOff   8          2m33s
pytorchjob-example-bq7fbhnb-worker-0         0/1     Init:1/2           0          2m34s
pytorchjob-example-bq7fbhnb-worker-1         0/1     Init:1/2           0          2m33s
pytorchjob-example-r72dqchj-master-0         0/2     CrashLoopBackOff   8          2m32s
pytorchjob-example-r72dqchj-worker-0         0/1     Init:1/2           0          2m33s
pytorchjob-example-r72dqchj-worker-1         0/1     Init:1/2           0          2m32s
pytorchjob-example-random-754f4df755-k8sv4   1/1     Running            0          3m1s
```

When I execute a command `describe pod`, I got the following error message:
`Warning  Failed     2m24s (x3 over 2m43s)  kubelet, minikube  Error: failed to start container "pytorch": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown`
Setting "--no-cuda=True" gave the same result.
Any advice on how to solve the problem would be appreciated.
```
vagrant@minikf:~$ kubectl describe pod pytorchjob-example-82cjcqdz-master-0 -n kubeflow-user
Name:               pytorchjob-example-82cjcqdz-master-0
Namespace:          kubeflow-user
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.10.10.10
Start Time:         Sun, 22 Mar 2020 05:37:07 -0700
Labels:             controller-name=pytorch-operator
                    group-name=kubeflow.org
                    job-name=pytorchjob-example-82cjcqdz
                    job-role=master
                    pytorch-job-name=pytorchjob-example-82cjcqdz
                    pytorch-replica-index=0
                    pytorch-replica-type=master
Annotations:        sidecar.istio.io/inject: false
Status:             Running
IP:                 172.17.0.75
Controlled By:      PyTorchJob/pytorchjob-example-82cjcqdz
Init Containers:
  startup-lock-init-container:
    Container ID:  docker://98c5c77c6d76d30e6e4bc8f9d84d1a5fd8aa1f8915189acfc504806335f50bc5
    Image:         gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21
    Image ID:      docker-pullable://gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21
    Port:          <none>
    Host Port:     <none>
    Args:
      --host
      $(HOST_IP)
      --port
      10101
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 22 Mar 2020 05:37:16 -0700
      Finished:     Sun, 22 Mar 2020 05:37:30 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      HOST_IP:   (v1:status.hostIP)
    Mounts:     <none>
Containers:
  pytorch:
    Container ID:  docker://ace5e78b3f5e2fff5c112ebc6023809d5d4ee1846608e31ac165fdf37a9b9c48
    Image:         gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
    Image ID:      docker-pullable://gcr.io/kubeflow-ci/pytorch-dist-mnist-test@sha256:40c36403ad68c1ed043d52366adaba75c1e02b0f4f3b82c58f0eb6df6fe7802d
    Port:          23456/TCP
    Host Port:     0/TCP
    Command:
      sh
      -c
    Args:
      python /var/mnist.py --lr=0.02568361122315596 --momentum=0.845009060208425 1>/var/log/katib/metrics.log 2>&1 && echo completed > /var/log/katib/$$$$.pid
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
      Exit Code:    128
      Started:      Sun, 22 Mar 2020 05:38:58 -0700
      Finished:     Sun, 22 Mar 2020 05:38:58 -0700
    Ready:          False
    Restart Count:  4
    Requests:
      cpu:     1m
      memory:  1M
    Environment:
      MASTER_PORT:       23456
      MASTER_ADDR:       localhost
      WORLD_SIZE:        3
      RANK:              0
      PYTHONUNBUFFERED:  0
    Mounts:
      /var/log/katib from metrics-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bskgc (ro)
  metrics-logger-and-collector:
    Container ID:  docker://4ee5308d8b1d6e85d123e03fb370cfd148b9f0e6cbc728cab82ad5c751b44f9a
    Image:         gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.8.0
    Image ID:      docker-pullable://gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector@sha256:9869c814da18054ee339f25229a72a74c962e077c8fa8b099ecf3f60d495d13d
    Port:          <none>
    Host Port:     <none>
    Args:
      -t
      pytorchjob-example-82cjcqdz
      -m
      accuracy
      -s
      katib-db-manager.kubeflow:6789
      -path
      /var/log/katib/metrics.log
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Sun, 22 Mar 2020 05:39:00 -0700
      Finished:     Sun, 22 Mar 2020 05:39:00 -0700
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:                500m
      ephemeral-storage:  5Gi
      memory:             100Mi
    Requests:
      cpu:                50m
      ephemeral-storage:  500Mi
      memory:             10Mi
    Environment:          <none>
    Mounts:
      /var/log/katib from metrics-volume (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-bskgc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bskgc
    Optional:    false
  metrics-volume:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m8s                   default-scheduler  Successfully assigned kubeflow-user/pytorchjob-example-82cjcqdz-master-0 to minikube
  Normal   Pulled     3m3s                   kubelet, minikube  Container image "gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21" already present on machine
  Normal   Created    3m2s                   kubelet, minikube  Created container startup-lock-init-container
  Normal   Started    2m59s                  kubelet, minikube  Started container startup-lock-init-container
  Normal   Pulled     2m24s (x3 over 2m44s)  kubelet, minikube  Container image "gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0" already present on machine
  Normal   Created    2m24s (x3 over 2m44s)  kubelet, minikube  Created container pytorch
  Warning  Failed     2m24s (x3 over 2m43s)  kubelet, minikube  Error: failed to start container "pytorch": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
  Normal   Pulled     2m24s (x3 over 2m43s)  kubelet, minikube  Container image "gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.8.0" already present on machine
  Normal   Created    2m24s (x3 over 2m43s)  kubelet, minikube  Created container metrics-logger-and-collector
  Normal   Started    2m24s (x3 over 2m42s)  kubelet, minikube  Started container metrics-logger-and-collector
  Warning  BackOff    2m23s (x2 over 2m39s)  kubelet, minikube  Back-off restarting failed container
  Warning  BackOff    2m23s (x2 over 2m39s)  kubelet, minikube  Back-off restarting failed container
```
```
vagrant@minikf:~$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
8a28c3bf1e34        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-r72dqchj-worker-0_kubeflow-user_d72bafed-6c39-11ea-9aa9-08002743284b_0
a604c0590ceb        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-82cjcqdz-worker-0_kubeflow-user_d85159e3-6c39-11ea-9aa9-08002743284b_0
cd09b0359745        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-bq7fbhnb-worker-1_kubeflow-user_d6cd83de-6c39-11ea-9aa9-08002743284b_0
d36dc1dc80cc        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-bq7fbhnb-worker-0_kubeflow-user_d6baefb2-6c39-11ea-9aa9-08002743284b_0
815a605908a5        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-82cjcqdz-worker-1_kubeflow-user_d898c73e-6c39-11ea-9aa9-08002743284b_0
5a0b898e5ea2        af341ccd2df8           "sh -c 'until nslook…"   19 minutes ago      Up 19 minutes                           k8s_init-pytorch_pytorchjob-example-r72dqchj-worker-1_kubeflow-user_d7614d7a-6c39-11ea-9aa9-08002743284b_0
2329362e362c        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-82cjcqdz-worker-1_kubeflow-user_d898c73e-6c39-11ea-9aa9-08002743284b_0
643508dcaef6        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-82cjcqdz-worker-0_kubeflow-user_d85159e3-6c39-11ea-9aa9-08002743284b_0
c200f6129222        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-82cjcqdz-master-0_kubeflow-user_d7d116fe-6c39-11ea-9aa9-08002743284b_0
1d249babf592        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-r72dqchj-worker-0_kubeflow-user_d72bafed-6c39-11ea-9aa9-08002743284b_0
2b2b79de0e3e        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-r72dqchj-master-0_kubeflow-user_d78be724-6c39-11ea-9aa9-08002743284b_0
145cd3ec78f6        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-r72dqchj-worker-1_kubeflow-user_d7614d7a-6c39-11ea-9aa9-08002743284b_0
ddaf1091935d        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-bq7fbhnb-worker-1_kubeflow-user_d6cd83de-6c39-11ea-9aa9-08002743284b_0
8674a90c41ea        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-bq7fbhnb-master-0_kubeflow-user_d6e94956-6c39-11ea-9aa9-08002743284b_0
8160318af71c        k8s.gcr.io/pause:3.1   "/pause"                 19 minutes ago      Up 19 minutes                           k8s_POD_pytorchjob-example-bq7fbhnb-worker-0_kubeflow-user_d6baefb2-6c39-11ea-9aa9-08002743284b_0
45c384728426        56c0051f100c           "python main.py"         20 minutes ago      Up 19 minutes                           k8s_suggestion_pytorchjob-example-random-754f4df755-k8sv4_kubeflow-user_c68126bc-6c39-11ea-9aa9-08002743284b_0
3d71af00878c        k8s.gcr.io/pause:3.1   "/pause"                 20 minutes ago      Up 20 minutes                           k8s_POD_pytorchjob-example-random-754f4df755-k8sv4_kubeflow-user_c68126bc-6c39-11ea-9aa9-0800274328
```
```
vagrant@minikf:~$ docker logs 8a28c3bf1e34
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'pytorchjob-example-r72dqchj-master-0': Name does not resolve
waiting for master

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'pytorchjob-example-r72dqchj-master-0': Name does not resolve
waiting for master

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'pytorchjob-example-r72dqchj-master-0': Name does not resolve
waiting for master

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'pytorchjob-example-r72dqchj-master-0': Name does not resolve
waiting for master
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'pytorchjob-example-r72dqchj-master-0': Name does not resolve
waiting for master
nslookup: can't resolve '(null)': Name does not resolve
```

**Environment:**
- Katib version: v1alpha3
gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui v0.8.0 540d9308c9f6 4 weeks ago 54.4MB
gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector v0.8.0 ff9ce96cf37c 4 weeks ago 25.2MB
gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller v0.8.0 7c5162abd775 4 weeks ago 53.8MB
gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt v0.8.0 56c0051f100c 4 weeks ago 1.23GB
gcr.io/kubeflow-images-public/katib/v1alpha3/katib-db-manager v0.8.0 32229959fe81 4 weeks ago 28.5MB
- MiniKF box version:
arrikto/minikf (virtualbox, 20200305.1.0)
- Kubeflow version:
- Minikube version: v1.2.0
- Kubernetes version: (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):

**Comment by andreyvelich** [comment]
@devxoxo I tried to run pytorch example, for me it was succeeded. I was using GKE cluster without GPU. I didn't specify `--no-cuda` flag.

Can you show me the logs from the `pytorchjob-example-82cjcqdz-master-0` container, like you did `describe` ?

Also, try to run pytorch job from this yaml file with default values:

```yaml
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-job
  namespace: kubeflow-user
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
              imagePullPolicy: Always
              command:
                - "python"
                - "/var/mnist.py"
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
              imagePullPolicy: Always
              command:
                - "python"
                - "/var/mnist.py"
```

**Comment by devxoxo** [comment]
The pod has been deleted and reproduced.
Please note that the container id is different.
As you can see, there are no logs.
```
vagrant@minikf:~$ kubectl get pods -n kubeflow-user
NAME                                         READY   STATUS             RESTARTS   AGE
pytorchjob-example-lmfrjh5l-master-0         0/2     CrashLoopBackOff   14         11m
pytorchjob-example-lmfrjh5l-worker-0         0/1     Init:1/2           0          11m
pytorchjob-example-lmfrjh5l-worker-1         0/1     Init:1/2           0          11m
pytorchjob-example-pbtt4t8x-master-0         0/2     CrashLoopBackOff   14         11m
pytorchjob-example-pbtt4t8x-worker-0         0/1     Init:1/2           0          11m
pytorchjob-example-pbtt4t8x-worker-1         0/1     Init:1/2           0          11m
pytorchjob-example-random-754f4df755-k29cp   1/1     Running            0          11m
pytorchjob-example-t8x8pnd8-master-0         0/2     CrashLoopBackOff   14         11m
pytorchjob-example-t8x8pnd8-worker-0         0/1     Init:1/2           0          11m
pytorchjob-example-t8x8pnd8-worker-1         0/1     Init:1/2           0          11m
```
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
d72df367a463        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-pbtt4t8x-worker-1_kubeflow-user_02266e42-705a-11ea-96eb-080027a9df3a_0
e616828af1f2        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-t8x8pnd8-worker-0_kubeflow-user_0122a2d6-705a-11ea-96eb-080027a9df3a_0
8c18468986d0        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-pbtt4t8x-worker-0_kubeflow-user_01f9ae12-705a-11ea-96eb-080027a9df3a_0
e41b8127d651        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-lmfrjh5l-worker-1_kubeflow-user_00cdbdbd-705a-11ea-96eb-080027a9df3a_0
ac617b93749f        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-lmfrjh5l-worker-0_kubeflow-user_00a1d238-705a-11ea-96eb-080027a9df3a_0
6a29dacb22d2        af341ccd2df8           "sh -c 'until nslook…"   11 minutes ago      Up 11 minutes                           k8s_init-pytorch_pytorchjob-example-t8x8pnd8-worker-1_kubeflow-user_015a2fa9-705a-11ea-96eb-080027a9df3a_0
b2f835ff2258        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-pbtt4t8x-worker-1_kubeflow-user_02266e42-705a-11ea-96eb-080027a9df3a_0
19b0a5733262        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-pbtt4t8x-worker-0_kubeflow-user_01f9ae12-705a-11ea-96eb-080027a9df3a_0
0675b275cc5a        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-pbtt4t8x-master-0_kubeflow-user_01ae9ec5-705a-11ea-96eb-080027a9df3a_0
14a002b613eb        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-t8x8pnd8-worker-1_kubeflow-user_015a2fa9-705a-11ea-96eb-080027a9df3a_0
d0044e843365        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-t8x8pnd8-worker-0_kubeflow-user_0122a2d6-705a-11ea-96eb-080027a9df3a_0
53735696a950        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-t8x8pnd8-master-0_kubeflow-user_00ecebe0-705a-11ea-96eb-080027a9df3a_0
5c499342e04e        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-lmfrjh5l-worker-1_kubeflow-user_00cdbdbd-705a-11ea-96eb-080027a9df3a_0
16c3c88e7712        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-lmfrjh5l-worker-0_kubeflow-user_00a1d238-705a-11ea-96eb-080027a9df3a_0
1e4228e60229        k8s.gcr.io/pause:3.1   "/pause"                 11 minutes ago      Up 11 minutes                           k8s_POD_pytorchjob-example-lmfrjh5l-master-0_kubeflow-user_005f388c-705a-11ea-96eb-080027a9df3a_0
04de6e81800c        56c0051f100c           "python main.py"         12 minutes ago      Up 12 minutes                           k8s_suggestion_pytorchjob-example-random-754f4df755-k29cp_kubeflow-user_f299686e-7059-11ea-96eb-080027a9df3a_0
dc0a5847bc59        k8s.gcr.io/pause:3.1   "/pause"                 12 minutes ago      Up 12 minutes                           k8s_POD_pytorchjob-example-random-754f4df755-k29cp_kubeflow-user_f299686e-7059-11ea-96eb-080027a9df3a_0
```
```
vagrant@minikf:~$ docker logs 0675b275cc5a
vagrant@minikf:~$ docker logs b2f835ff2258
vagrant@minikf:~$ docker logs b2f835ff2258
vagrant@minikf:~$ 
```

[The yaml file](https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/pytorchjob-example.yaml) I ran is as follows.
I didn't specify --no-cuda flag.
```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow-user
  name: pytorchjob-example
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: --momentum
      parameterType: double
      feasibleSpace:
        min: "0.5"
        max: "0.9"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: PyTorchJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           pytorchReplicaSpecs:
            Master:
              replicas: 1
              restartPolicy: OnFailure
              template:
                spec:
                  containers:
                    - name: pytorch
                      image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "/var/mnist.py"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
            Worker:
              replicas: 2
              restartPolicy: OnFailure
              template:
                spec:
                  containers:
                    - name: pytorch
                      image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "/var/mnist.py"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
```

**Comment by andreyvelich** [comment]
Can you run this: `kubectl logs <master training container pod name> -n kubeflow-user -c metrics-logger-and-collector`.

In the screenshot above, your master training container pod name is:
`pytorchjob-example-lmfrjh5l-master-0`

**Comment by devxoxo** [comment]
This is the result of `kubectl logs`:
```
vagrant@minikf:~$ kubectl get pods -n kubeflow-user
NAME                                         READY   STATUS             RESTARTS   AGE
pytorchjob-example-6b8fzzxb-master-0         0/2     CrashLoopBackOff   8          3m7s
pytorchjob-example-6b8fzzxb-worker-0         0/1     Init:1/2           0          3m6s
pytorchjob-example-6b8fzzxb-worker-1         0/1     Init:1/2           0          3m6s
pytorchjob-example-72qq2zwc-master-0         0/2     CrashLoopBackOff   8          3m5s
pytorchjob-example-72qq2zwc-worker-0         0/1     Init:1/2           0          3m5s
pytorchjob-example-72qq2zwc-worker-1         0/1     Init:1/2           0          3m5s
pytorchjob-example-7k8sqp4b-master-0         0/2     CrashLoopBackOff   8          3m6s
pytorchjob-example-7k8sqp4b-worker-0         0/1     Init:1/2           0          3m5s
pytorchjob-example-7k8sqp4b-worker-1         0/1     Init:1/2           0          3m5s
pytorchjob-example-random-754f4df755-qsn62   1/1     Running            0          3m28s
```
```
vagrant@minikf:~$ kubectl logs pytorchjob-example-6b8fzzxb-master-0 -n kubeflow-user -c metrics-logger-and-collector
I0327 19:30:56.354289     106 main.go:85] Trial Name: pytorchjob-example-6b8fzzxb
F0327 19:30:56.363349     106 main.go:119] Failed to collect logs: open /var/log/katib/metrics.log: no such file or directory
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc000182100, 0xc0001a2000, 0x7e, 0xa7)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb8
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0x129da40, 0xc000000003, 0xc000163030, 0x12378d6, 0x7, 0x77, 0x0)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2d0
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0x129da40, 0x7fff00000003, 0xc6efab, 0x1a, 0xc00013df18, 0x1, 0x1)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
	/go/src/github.com/kubeflow/katib/cmd/metricscollector/v1alpha3/file-metricscollector/main.go:119 +0x511
```

**Comment by andreyvelich** [comment]
@devxoxo Can you try to run just PytorchJob, from the yaml, that I mentioned here: https://github.com/kubeflow/katib/issues/1112#issuecomment-605100997 ?
After that, check the logs from the master pod.

**Comment by devxoxo** [comment]
@andreyvelich When I tried to run [the yaml](https://github.com/kubeflow/katib/issues/1112#issuecomment-605100997), 
I got the following error message: `admission webhook "validating.experiment.katib.kubeflow.org" denied the request: No spec.objective specified.`
<img width="1680" alt="스크린샷 2020-03-30 오후 11 17 04" src="https://user-images.githubusercontent.com/59082302/77925177-8140c300-72df-11ea-86df-2b46b9d47d34.png">

When I tried to add the yaml file in the Trial Manifests tab and then select it in the Parameters tab, I got the following error message: `admission webhook "validating.experiment.katib.kubeflow.org" denied the request: Invalid spec.trialTemplate: metadata.name should be {{.Trial}}`
<img width="1680" alt="스크린샷 2020-03-30 오후 11 36 38" src="https://user-images.githubusercontent.com/59082302/77925397-c533c800-72df-11ea-82ab-719fc1e9142a.png">

Did I run the yaml in the wrong way you didn't intend?

**Comment by andreyvelich** [comment]
Yeah. I just want to run PytorchJob without Katib. You can't do it from the Katib UI.

Do you have access to your Kubernetes cluster?
If yes, can you just create file with this yaml and run:
`kubectl create -f <path to the file with yaml>`

**Comment by devxoxo** [comment]
This is the result of not using the Katib UI.
In my case it seems to be giving the same error as before.
```
vagrant@minikf:~$ kubectl get pods -n kubeflow-user
NAME                                           READY   STATUS             RESTARTS   AGE
pytorch-job-master-0                           1/2     CrashLoopBackOff   5          3m55s
pytorch-job-worker-0                           0/2     Init:1/3           0          12m
pytorch-job-worker-1                           0/2     Init:1/3           0          12m
```
```
vagrant@minikf:~$ kubectl logs pytorch-job-master-0 -n kubeflow-user -c metrics-logger-and-collector
Error from server (BadRequest): container metrics-logger-and-collector is not valid for pod pytorch-job-master-0
```
```
vagrant@minikf:~$ kubectl describe pod pytorch-job-master-0 -n kubeflow-user
Name:               pytorch-job-master-0
Namespace:          kubeflow-user
Priority:           0
PriorityClassName:  <none>
Node:               minikube/10.10.10.10
Start Time:         Sat, 28 Mar 2020 02:17:42 -0700
Labels:             controller-name=pytorch-operator
                    group-name=kubeflow.org
                    job-name=pytorch-job
                    job-role=master
                    pytorch-job-name=pytorch-job
                    pytorch-replica-index=0
                    pytorch-replica-type=master
Annotations:        sidecar.istio.io/status:
                      {"version":"2696c96840179bdcd8f86ed60a643396f0cb250f56458b46a7fc667e6c75ef7f","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:             Running
IP:                 172.17.0.68
Controlled By:      PyTorchJob/pytorch-job
Init Containers:
  startup-lock-init-container:
    Container ID:  docker://856010b57044fe85652490726d4ce178b84d32980c7de9f9b133b7e482acc8ce
    Image:         gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21
    Image ID:      docker-pullable://gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21
    Port:          <none>
    Host Port:     <none>
    Args:
      --host
      $(HOST_IP)
      --port
      10101
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 28 Mar 2020 02:17:44 -0700
      Finished:     Sat, 28 Mar 2020 02:17:44 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      HOST_IP:   (v1:status.hostIP)
    Mounts:     <none>
  istio-init:
    Container ID:  docker://c500d822abaede2caa5a8c8fc4076dd349b2a5ba102dd3e0614929c384e8b999
    Image:         gcr.io/istio-release/proxy_init:release-1.3-latest-daily
    Image ID:      docker-pullable://gcr.io/istio-release/proxy_init@sha256:5c4489204016425da102d18ec31111d2fc56c787575f55582c7c5fcf69fd09df
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 28 Mar 2020 02:17:45 -0700
      Finished:     Sat, 28 Mar 2020 02:17:46 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:       <none>
Containers:
  pytorch:
    Container ID:  docker://801493f678793d46208eed19feb7c701c89c2add409de54aa5b620d6272d4dd5
    Image:         gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
    Image ID:      docker-pullable://gcr.io/kubeflow-ci/pytorch-dist-mnist-test@sha256:40c36403ad68c1ed043d52366adaba75c1e02b0f4f3b82c58f0eb6df6fe7802d
    Port:          23456/TCP
    Host Port:     0/TCP
    Command:
      python
      /var/mnist.py
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
      Exit Code:    128
      Started:      Sat, 28 Mar 2020 02:23:32 -0700
      Finished:     Sat, 28 Mar 2020 02:23:32 -0700
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:     1m
      memory:  1M
    Environment:
      MASTER_PORT:       23456
      MASTER_ADDR:       localhost
      WORLD_SIZE:        3
      RANK:              0
      PYTHONUNBUFFERED:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pbkzc (ro)
  istio-proxy:
    Container ID:  docker://149bfe51d042c89588d4d3d98b2f2a8fff1046ae718cf102f3ae1e5784d833b5
    Image:         gcr.io/istio-release/proxyv2:release-1.3-latest-daily
    Image ID:      docker-pullable://gcr.io/istio-release/proxyv2@sha256:de1bcf19d8d709dc6c66aab1d2b9f13f27626b86ab0690a015fb4c72b062eb1d
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      pytorch-job-master-0.kubeflow-user
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15011
      --zipkinAddress
      zipkin.istio-system:9411
      --dnsRefreshRate
      300s
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --statusPort
      15020
      --applicationPorts
      23456
    State:          Running
      Started:      Sat, 28 Mar 2020 02:17:47 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                          pytorch-job-master-0 (v1:metadata.name)
      ISTIO_META_POD_PORTS:              [
                                             {"name":"pytorchjob-port","containerPort":23456,"protocol":"TCP"}
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      POD_NAMESPACE:                     kubeflow-user (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:               pytorch-job-master-0 (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       kubeflow-user (v1:metadata.namespace)
      SDS_ENABLED:                       true
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  23456
      ISTIO_METAJSON_LABELS:             {"controller-name":"pytorch-operator","group-name":"kubeflow.org","job-name":"pytorch-job","job-role":"master","pytorch-job-name":"pytorch-job","pytorch-replica-index":"0","pytorch-replica-type":"master"}
                                         
      ISTIO_META_WORKLOAD_NAME:          pytorch-job-master-0
      ISTIO_META_OWNER:                  kubernetes://api/v1/namespaces/kubeflow-user/pods/pytorch-job-master-0
    Mounts:
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/sds from sds-uds-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pbkzc (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-pbkzc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pbkzc
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  sds-uds-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/sds
    HostPathType:  
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute for 300s
                             node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m40s                   default-scheduler  Successfully assigned kubeflow-user/pytorch-job-master-0 to minikube
  Normal   Created    9m38s                   kubelet, minikube  Created container startup-lock-init-container
  Normal   Started    9m38s                   kubelet, minikube  Started container startup-lock-init-container
  Normal   Pulled     9m38s                   kubelet, minikube  Container image "gcr.io/arrikto-public/startup-lock-init@sha256:0fbe996a2f6b380d7c566ba16255ec034faec983c2661da778fe09b3e744ad21" already present on machine
  Normal   Started    9m37s                   kubelet, minikube  Started container istio-init
  Normal   Pulled     9m37s                   kubelet, minikube  Container image "gcr.io/istio-release/proxy_init:release-1.3-latest-daily" already present on machine
  Normal   Created    9m37s                   kubelet, minikube  Created container istio-init
  Normal   Pulled     9m36s                   kubelet, minikube  Container image "gcr.io/istio-release/proxyv2:release-1.3-latest-daily" already present on machine
  Normal   Created    9m36s                   kubelet, minikube  Created container istio-proxy
  Normal   Started    9m35s                   kubelet, minikube  Started container istio-proxy
  Normal   Pulled     8m51s (x4 over 9m36s)   kubelet, minikube  Container image "gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0" already present on machine
  Warning  Failed     8m51s (x4 over 9m36s)   kubelet, minikube  Error: failed to start container "pytorch": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown
  Normal   Created    8m51s (x4 over 9m36s)   kubelet, minikube  Created container pytorch
  Warning  BackOff    4m25s (x23 over 9m34s)  kubelet, minikube  Back-off restarting failed container
```

**Comment by andreyvelich** [comment]
Thank you for running this.

Can you check the logs from the master like this:
`kubectl logs pytorch-job-master-0 -n kubeflow-user -c pytorch`

**Comment by devxoxo** [comment]
I'm not sure why, but I didn't see any results like this:
vagrant@minikf:~$ kubectl logs pytorch-job-master-0 -n kubeflow-user -c pytorch
vagrant@minikf:~$

**Comment by andreyvelich** [comment]
@devxoxo Strange. Maybe you have old version of the image. Try to delete pytorch training container image from your machine:
`docker image rm gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0`
Also disable istio-proxy from pytorch job.
Delete job and deploy it again with this yaml:
```yaml
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-job
  namespace: kubeflow-user
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": false
        spec:
          containers:
            - name: pytorch
              image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
              imagePullPolicy: Always
              command:
                - "python"
                - "/var/mnist.py"
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            "sidecar.istio.io/inject": false
        spec:
          containers:
            - name: pytorch
              image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
              imagePullPolicy: Always
              command:
                - "python"
                - "/var/mnist.py"
```

**Comment by devxoxo** [comment]
I don't know the exact reason, but in my case,
The methods you suggested did not work.
Instead, I changed the base image from pytorch/pytorch: 1.0-cuda10.0-cudnn7-runtime to mapler/pytorch-cpu and it worked.

**Comment by andreyvelich** [comment]
Do you mean changed base image in `Dockerfile` for training container?

**Comment by devxoxo** [comment]
Yes, that's what I said.

**Comment by andreyvelich** [comment]
@devxoxo Please, can you give me the link to the Training container source code that you used while building the image?

**Comment by devxoxo** [comment]
This code only removes the gpu-related settings from the code in this [link](https://github.com/kubeflow/pytorch-operator/blob/master/examples/mnist/mnist.py).
```
from __future__ import print_function

import argparse
import os

from tensorboardX import SummaryWriter
from torchvision import datasets, transforms
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

WORLD_SIZE = int(os.environ.get('WORLD_SIZE', 1))

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4 * 4 * 50, 500)
        self.fc2 = nn.Linear(500, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4 * 4 * 50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)

def train(args, model, device, train_loader, optimizer, epoch, writer):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tloss={:.4f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                       100. * batch_idx / len(train_loader), loss.item()))
            niter = epoch * len(train_loader) + batch_idx
            writer.add_scalar('loss', loss.item(), niter)


def test(args, model, device, test_loader, writer, epoch):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.nll_loss(output, target, reduction='sum').item()  # sum up batch loss
            pred = output.max(1, keepdim=True)[1]  # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    print('\naccuracy={:.4f}\n'.format(float(correct) / len(test_loader.dataset)))
    writer.add_scalar('accuracy', float(correct) / len(test_loader.dataset), epoch)


def should_distribute():
    return dist.is_available() and WORLD_SIZE > 1


def is_distributed():
    return dist.is_available() and dist.is_initialized()


def main():
    # Training settings
    parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
    parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                        help='input batch size for training (default: 64)')
    parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                        help='input batch size for testing (default: 1000)')
    parser.add_argument('--epochs', type=int, default=1, metavar='N',
                        help='number of epochs to train (default: 10)')
    parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                        help='learning rate (default: 0.01)')
    parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                        help='SGD momentum (default: 0.5)')
    parser.add_argument('--seed', type=int, default=1, metavar='S',
                        help='random seed (default: 1)')
    parser.add_argument('--log-interval', type=int, default=10, metavar='N',
                        help='how many batches to wait before logging training status')
    parser.add_argument('--save-model', action='store_true', default=False,
                        help='For Saving the current Model')
    parser.add_argument('--dir', default='logs', metavar='L',
                        help='directory where summary logs are stored')
    if dist.is_available():
        parser.add_argument('--backend', type=str, help='Distributed backend',
                            choices=[dist.Backend.GLOO, dist.Backend.NCCL, dist.Backend.MPI],
                            default=dist.Backend.GLOO)
    args = parser.parse_args()

    writer = SummaryWriter(args.dir)

    torch.manual_seed(args.seed)

    device = torch.device("cpu")

    if should_distribute():
        print('Using distributed PyTorch with {} backend'.format(args.backend))
        dist.init_process_group(backend=args.backend)

    kwargs = {}
    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ])),
        batch_size=args.batch_size, shuffle=True, **kwargs)
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])),
        batch_size=args.test_batch_size, shuffle=False, **kwargs)

    model = Net().to(device)

    if is_distributed():
        Distributor = nn.parallel.DistributedDataParallelCPU
        model = Distributor(model)

    optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)

    for epoch in range(1, args.epochs + 1):
        train(args, model, device, train_loader, optimizer, epoch, writer)
        test(args, model, device, test_loader, writer, epoch)

    if (args.save_model):
        torch.save(model.state_dict(), "mnist_cnn.pt")


if __name__ == '__main__':
    main()
```

And I installed minikf as explained in the following link
https://www.arrikto.com/minikf/
